name: Bug report
description: Report a problem
title: "[BUG] "
labels: bug

body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the issue

  - type: textarea
    attributes:
      label: Steps to reproduce

  - type: textarea
    attributes:
      label: Expected behavior
